Add fs persistence layer
jeffa5/automerge-persistent pull request #13
Opened 2022-04-29 20:01 UTC by jeromegn

Adds a filesystem persistence layer.

There are some particularities to it:
- It has both a sync and async interface for flushing. The latter is behind a feature flag.
- It only writes to disk when `flush`ed, else it's like the memory store (this is for performance reasons)
  - This is similar to the `sled` strategy

Along, I made changes to the main lib:
- Added `persister_mut()` (useful for the flushing I'm talking about)
- Added `transact_with()`
- Added `apply_changes` and `apply_changes_with`
- Changed the `reset_sync_state` logic to actually call the persister's function so it wouldn't only be removed from memory, but also from the store.

Happy to make changes! Let me know what you think.

2022-08-02 22:13 UTC, tombh commented
Whilst I haven't been able to use this code as is, I've certainly taken inspiration from it, thank you!

I wonder what the state of this repo is? Would be nice to pool our resources if we're all doing similar things ❤️

2022-08-03 19:22 UTC, jeffa5 requested changes
Thanks so much for this and sorry I've taken so long to get to it. Could you maybe follow up with the one comment and rebase to fix the conflicts?

Looking forward to having this in!

2022-08-03 19:22 UTC, jeffa5 commented on automerge-persistent-fs/src/lib.rs
> +    pub async fn flush(
Could we switch the `_sync` and async variants? Seems strange to have the non-default have an extension on the name.

2022-08-03 19:23 UTC, jeffa5 commented
> Whilst I haven't been able to use this code as is, I've certainly taken inspiration from it, thank you!
> 
> I wonder what the state of this repo is? Would be nice to pool our resources if we're all doing similar things :heart:

Hi @tombh, I agree about pooling the resources. I'm not sure whether it might help to eventually move some of the extra projects surrounding automerge to either the main automerge org or an automerge-community org?

2022-08-05 10:11 UTC, tombh commented
Yes, good question, either would be great, I suppose it depends on the nature and status of the project

2022-09-26 20:14 UTC, jeffa5 commented
Thank you @jeromegn  for the contribution, I've fixed it up and merged it in https://github.com/jeffa5/automerge-persistent/pull/15

2022-09-26 20:14 UTC, closed without merging